function xdot = fstatederivative(t, x)

% Define constants

% Define forces: 

% State assignments
q1 = x(1); q2 = x(2); q3 = x(3); q4 = x(4); q5 = x(5); q6 = x(6); 
u1 = x(7); u2 = x(8); u3 = x(9); u4 = x(10); u5 = x(11); u6 = x(12); 

c4 = cos(q4); c5 = cos(q5); c6 = cos(q6); s4 = sin(q4); s5 = sin(q5); s6 = sin(q6); c5m6 = cos(q5 - q6); s5m6 = sin(q5 - q6); 

MM = zeros(6,6); rhs = zeros(6,1);

% Mass Matrix
MM(1,1) = MLeg + MPelvis + MShank + MThigh; MM(1,2) = 0; MM(1,3) = 0; MM(1,4) ...
= -((s4*legMassForwardOffset + c4*legMassVerticalOffsetBelowPelvis)*MLeg); ...
MM(1,5) = -(s5*MThigh*swingThighMassForwardOffset) - c5*(LThigh*MShank + ...
MThigh*swingThighMassVerticalOffsetBelowPelvis); MM(1,6) = ...
-(MShank*(s6*swingShankMassForwardOffset + ...
c6*swingShankMassVerticalOffsetBelowPelvis)); 
MM(2,1) = MM(1,2); MM(2,2) = MLeg + MPelvis + MShank + MThigh; MM(2,3) = 0; ...
MM(2,4) = -(c4*legMassForwardOffset*MLeg) + ...
s4*legMassVerticalOffsetBelowPelvis*MLeg; MM(2,5) = ...
-(c5*MThigh*swingThighMassForwardOffset) + s5*(LThigh*MShank + ...
MThigh*swingThighMassVerticalOffsetBelowPelvis); MM(2,6) = ...
-(c6*MShank*swingShankMassForwardOffset) + ...
s6*MShank*swingShankMassVerticalOffsetBelowPelvis; 
MM(3,1) = MM(1,3); MM(3,2) = MM(2,3); MM(3,3) = IPelvis; MM(3,4) = 0; MM(3,5) ...
= 0; MM(3,6) = 0; 
MM(4,1) = MM(1,4); MM(4,2) = MM(2,4); MM(4,3) = MM(3,4); MM(4,4) = ILeg + ...
MLeg*(legMassForwardOffset*legMassForwardOffset + ...
legMassVerticalOffsetBelowPelvis*legMassVerticalOffsetBelowPelvis); MM(4,5) = ...
0; MM(4,6) = 0; 
MM(5,1) = MM(1,5); MM(5,2) = MM(2,5); MM(5,3) = MM(3,5); MM(5,4) = MM(4,5); ...
MM(5,5) = IThigh + MShank*(LThigh*LThigh) + ...
MThigh*(swingThighMassForwardOffset*swingThighMassForwardOffset + ...
swingThighMassVerticalOffsetBelowPelvis*swingThighMassVerticalOffsetBelowPelvis); MM(5,6) = LThigh*MShank*(-(s5m6*swingShankMassForwardOffset) + c5m6*swingShankMassVerticalOffsetBelowPelvis); ...

MM(6,1) = MM(1,6); MM(6,2) = MM(2,6); MM(6,3) = MM(3,6); MM(6,4) = MM(4,6); ...
MM(6,5) = MM(5,6); MM(6,6) = IShank + ...
MShank*(swingShankMassForwardOffset*swingShankMassForwardOffset + ...
swingShankMassVerticalOffsetBelowPelvis*swingShankMassVerticalOffsetBelowPelvis); ...


% righthand side terms
rhs(1) = (c4*legMassForwardOffset - ...
s4*legMassVerticalOffsetBelowPelvis)*MLeg*(u4*u4) + ...
(c5*MThigh*swingThighMassForwardOffset - s5*(LThigh*MShank + ...
MThigh*swingThighMassVerticalOffsetBelowPelvis))*(u5*u5) + ...
MShank*(c6*swingShankMassForwardOffset - ...
s6*swingShankMassVerticalOffsetBelowPelvis)*(u6*u6) + g*MLeg*sin(groundAngle) ...
+ g*MPelvis*sin(groundAngle) + g*MShank*sin(groundAngle) + ...
g*MThigh*sin(groundAngle); 
rhs(2) = -(g*MLeg*cos(groundAngle)) - g*MPelvis*cos(groundAngle) - ...
g*MShank*cos(groundAngle) - g*MThigh*cos(groundAngle) - ...
(s4*legMassForwardOffset + c4*legMassVerticalOffsetBelowPelvis)*MLeg*(u4*u4) ...
- (s5*MThigh*swingThighMassForwardOffset + c5*(LThigh*MShank + ...
MThigh*swingThighMassVerticalOffsetBelowPelvis))*(u5*u5) - ...
MShank*(s6*swingShankMassForwardOffset + ...
c6*swingShankMassVerticalOffsetBelowPelvis)*(u6*u6); 
rhs(3) = 0; 
rhs(4) = g*MLeg*(legMassForwardOffset*cos(q4 + groundAngle) - ...
legMassVerticalOffsetBelowPelvis*sin(q4 + groundAngle)); 
rhs(5) = -(LThigh*MShank*(c5m6*swingShankMassForwardOffset + ...
s5m6*swingShankMassVerticalOffsetBelowPelvis)*(u6*u6)) + ...
g*(MThigh*swingThighMassForwardOffset*cos(q5 + groundAngle) - (LThigh*MShank ...
+ MThigh*swingThighMassVerticalOffsetBelowPelvis)*sin(q5 + groundAngle)); 
rhs(6) = MShank*(LThigh*(c5m6*swingShankMassForwardOffset + ...
s5m6*swingShankMassVerticalOffsetBelowPelvis)*(u5*u5) + ...
g*(swingShankMassForwardOffset*cos(q6 + groundAngle) - ...
swingShankMassVerticalOffsetBelowPelvis*sin(q6 + groundAngle))); 

udot = MM\rhs;
xdot = [x(6+1:2*6); udot];

constraintJacobianKneeFree(1,1) = 1; constraintJacobianKneeFree(1,2) = 0; ...
constraintJacobianKneeFree(1,3) = 0; constraintJacobianKneeFree(1,4) = ...
-(c4*L); constraintJacobianKneeFree(1,5) = 0; constraintJacobianKneeFree(1,6) ...
= 0; 
constraintJacobianKneeFree(2,1) = 0; constraintJacobianKneeFree(2,2) = 1; ...
constraintJacobianKneeFree(2,3) = 0; constraintJacobianKneeFree(2,4) = s4*L; ...
constraintJacobianKneeFree(2,5) = 0; constraintJacobianKneeFree(2,6) = 0; 


constraintJacobianKneeFreeDot(1,1) = 0; constraintJacobianKneeFreeDot(1,2) = ...
0; constraintJacobianKneeFreeDot(1,3) = 0; constraintJacobianKneeFreeDot(1,4) ...
= s4*u4*L; constraintJacobianKneeFreeDot(1,5) = 0; ...
constraintJacobianKneeFreeDot(1,6) = 0; 
constraintJacobianKneeFreeDot(2,1) = 0; constraintJacobianKneeFreeDot(2,2) = ...
0; constraintJacobianKneeFreeDot(2,3) = 0; constraintJacobianKneeFreeDot(2,4) ...
= c4*u4*L; constraintJacobianKneeFreeDot(2,5) = 0; ...
constraintJacobianKneeFreeDot(2,6) = 0; 


constraintJacobianKneeLocked(1,1) = 1; constraintJacobianKneeLocked(1,2) = 0; ...
constraintJacobianKneeLocked(1,3) = 0; constraintJacobianKneeLocked(1,4) = ...
-(c4*L); constraintJacobianKneeLocked(1,5) = 0; ...
constraintJacobianKneeLocked(1,6) = 0; 
constraintJacobianKneeLocked(2,1) = 0; constraintJacobianKneeLocked(2,2) = 1; ...
constraintJacobianKneeLocked(2,3) = 0; constraintJacobianKneeLocked(2,4) = ...
s4*L; constraintJacobianKneeLocked(2,5) = 0; ...
constraintJacobianKneeLocked(2,6) = 0; 
constraintJacobianKneeLocked(3,1) = 0; constraintJacobianKneeLocked(3,2) = 0; ...
constraintJacobianKneeLocked(3,3) = 0; constraintJacobianKneeLocked(3,4) = 0; ...
constraintJacobianKneeLocked(3,5) = 1; constraintJacobianKneeLocked(3,6) = ...
-1; 


constraintJacobianKneeLockedDot(1,1) = 0; ...
constraintJacobianKneeLockedDot(1,2) = 0; ...
constraintJacobianKneeLockedDot(1,3) = 0; ...
constraintJacobianKneeLockedDot(1,4) = s4*u4*L; ...
constraintJacobianKneeLockedDot(1,5) = 0; ...
constraintJacobianKneeLockedDot(1,6) = 0; 
constraintJacobianKneeLockedDot(2,1) = 0; ...
constraintJacobianKneeLockedDot(2,2) = 0; ...
constraintJacobianKneeLockedDot(2,3) = 0; ...
constraintJacobianKneeLockedDot(2,4) = c4*u4*L; ...
constraintJacobianKneeLockedDot(2,5) = 0; ...
constraintJacobianKneeLockedDot(2,6) = 0; 
constraintJacobianKneeLockedDot(3,1) = 0; ...
constraintJacobianKneeLockedDot(3,2) = 0; ...
constraintJacobianKneeLockedDot(3,3) = 0; ...
constraintJacobianKneeLockedDot(3,4) = 0; ...
constraintJacobianKneeLockedDot(3,5) = 0; ...
constraintJacobianKneeLockedDot(3,6) = 0; 


PE = -(g*(-(q2*(MLeg + MPelvis + MShank + MThigh)*cos(groundAngle)) + ...
legMassVerticalOffsetBelowPelvis*MLeg*cos(q4 + groundAngle) + ...
LThigh*MShank*cos(q5 + groundAngle) + ...
MThigh*swingThighMassVerticalOffsetBelowPelvis*cos(q5 + groundAngle) + ...
MShank*swingShankMassVerticalOffsetBelowPelvis*cos(q6 + groundAngle) + ...
q1*(MLeg + MPelvis + MShank + MThigh)*sin(groundAngle) + ...
legMassForwardOffset*MLeg*sin(q4 + groundAngle) + ...
MThigh*swingThighMassForwardOffset*sin(q5 + groundAngle) + ...
MShank*swingShankMassForwardOffset*sin(q6 + groundAngle)));

PEGravity = -(g*(-(q2*(MLeg + MPelvis + MShank + MThigh)*cos(groundAngle)) + ...
legMassVerticalOffsetBelowPelvis*MLeg*cos(q4 + groundAngle) + ...
LThigh*MShank*cos(q5 + groundAngle) + ...
MThigh*swingThighMassVerticalOffsetBelowPelvis*cos(q5 + groundAngle) + ...
MShank*swingShankMassVerticalOffsetBelowPelvis*cos(q6 + groundAngle) + ...
q1*(MLeg + MPelvis + MShank + MThigh)*sin(groundAngle) + ...
legMassForwardOffset*MLeg*sin(q4 + groundAngle) + ...
MThigh*swingThighMassForwardOffset*sin(q5 + groundAngle) + ...
MShank*swingShankMassForwardOffset*sin(q6 + groundAngle)));

PESpring = 0;

KE = (IPelvis*(u3*u3) + ILeg*(u4*u4) + IThigh*(u5*u5) + IShank*(u6*u6))/2. + ...
(MPelvis*(u1*u1 + u2*u2) + MLeg*(-2*s4*u1*u4*legMassForwardOffset + ...
2*s4*u2*u4*legMassVerticalOffsetBelowPelvis + ...
c4*(-2*u2*u4*legMassForwardOffset - 2*u1*u4*legMassVerticalOffsetBelowPelvis) ...
+ u1*u1 + u2*u2 + u4*u4*(legMassForwardOffset*legMassForwardOffset) + ...
u4*u4*(legMassVerticalOffsetBelowPelvis*legMassVerticalOffsetBelowPelvis)) + ...
MThigh*(-2*s5*u1*u5*swingThighMassForwardOffset + ...
2*s5*u2*u5*swingThighMassVerticalOffsetBelowPelvis + ...
c5*(-2*u2*u5*swingThighMassForwardOffset - ...
2*u1*u5*swingThighMassVerticalOffsetBelowPelvis) + u1*u1 + u2*u2 + ...
u5*u5*(swingThighMassForwardOffset*swingThighMassForwardOffset) + ...
u5*u5*(swingThighMassVerticalOffsetBelowPelvis*swingThighMassVerticalOffsetBelowPelvis)) + MShank*(-2*s6*u1*u6*swingShankMassForwardOffset + 2*s6*u2*u6*swingShankMassVerticalOffsetBelowPelvis + c6*(-2*u2*u6*swingShankMassForwardOffset - 2*u1*u6*swingShankMassVerticalOffsetBelowPelvis) + 2*c5*u1*(-(u5*swingThighMassVerticalOffsetBelowPelvis) + u5*(-LThigh + swingThighMassVerticalOffsetBelowPelvis)) - 2*s5*u2*(-(u5*swingThighMassVerticalOffsetBelowPelvis) + u5*(-LThigh + swingThighMassVerticalOffsetBelowPelvis)) + 2*s5m6*u6*swingShankMassForwardOffset*(-(u5*swingThighMassVerticalOffsetBelowPelvis) + u5*(-LThigh + swingThighMassVerticalOffsetBelowPelvis)) - 2*c5m6*u6*swingShankMassVerticalOffsetBelowPelvis*(-(u5*swingThighMassVerticalOffsetBelowPelvis) + u5*(-LThigh + swingThighMassVerticalOffsetBelowPelvis)) + u1*u1 + u2*u2 + u6*u6*(swingShankMassForwardOffset*swingShankMassForwardOffset) + u6*u6*(swingShankMassVerticalOffsetBelowPelvis*swingShankMassVerticalOffsetBelowPelvis) + (-(u5*swingThighMassVerticalOffsetBelowPelvis) + u5*(-LThigh + swingThighMassVerticalOffsetBelowPelvis))*(-(u5*swingThighMassVerticalOffsetBelowPelvis) + u5*(-LThigh + ...
swingThighMassVerticalOffsetBelowPelvis))))/2.;

points.pelvis.position(1) = q1; 
points.pelvis.position(2) = 0; 
points.pelvis.position(3) = q2; 


points.pelvis.R(1,1) = cos(q3); points.pelvis.R(1,2) = 0; ...
points.pelvis.R(1,3) = sin(q3); 
points.pelvis.R(2,1) = 0; points.pelvis.R(2,2) = 1; points.pelvis.R(2,3) = 0; 
points.pelvis.R(3,1) = -sin(q3); points.pelvis.R(3,2) = 0; ...
points.pelvis.R(3,3) = cos(q3); 


points.stanceLeg.position(1) = q1 + c4*legMassForwardOffset - ...
s4*legMassVerticalOffsetBelowPelvis; 
points.stanceLeg.position(2) = 0; 
points.stanceLeg.position(3) = q2 - s4*legMassForwardOffset - ...
c4*legMassVerticalOffsetBelowPelvis; 


points.stanceLeg.R(1,1) = c4; points.stanceLeg.R(1,2) = 0; ...
points.stanceLeg.R(1,3) = s4; 
points.stanceLeg.R(2,1) = 0; points.stanceLeg.R(2,2) = 1; ...
points.stanceLeg.R(2,3) = 0; 
points.stanceLeg.R(3,1) = -s4; points.stanceLeg.R(3,2) = 0; ...
points.stanceLeg.R(3,3) = c4; 


points.swingThigh.position(1) = q1 + c5*swingThighMassForwardOffset - ...
s5*swingThighMassVerticalOffsetBelowPelvis; 
points.swingThigh.position(2) = 0; 
points.swingThigh.position(3) = q2 - s5*swingThighMassForwardOffset - ...
c5*swingThighMassVerticalOffsetBelowPelvis; 


points.swingThigh.R(1,1) = c5; points.swingThigh.R(1,2) = 0; ...
points.swingThigh.R(1,3) = s5; 
points.swingThigh.R(2,1) = 0; points.swingThigh.R(2,2) = 1; ...
points.swingThigh.R(2,3) = 0; 
points.swingThigh.R(3,1) = -s5; points.swingThigh.R(3,2) = 0; ...
points.swingThigh.R(3,3) = c5; 


points.swingShank.position(1) = q1 - s5*LThigh + ...
c6*swingShankMassForwardOffset - s6*swingShankMassVerticalOffsetBelowPelvis; 
points.swingShank.position(2) = 0; 
points.swingShank.position(3) = q2 - c5*LThigh - ...
s6*swingShankMassForwardOffset - c6*swingShankMassVerticalOffsetBelowPelvis; 


points.swingShank.R(1,1) = c6; points.swingShank.R(1,2) = 0; ...
points.swingShank.R(1,3) = s6; 
points.swingShank.R(2,1) = 0; points.swingShank.R(2,2) = 1; ...
points.swingShank.R(2,3) = 0; 
points.swingShank.R(3,1) = -s6; points.swingShank.R(3,2) = 0; ...
points.swingShank.R(3,3) = c6; 


points.stanceFootContactPoint(1) = q1 - s4*L; 
points.stanceFootContactPoint(2) = 0; 
points.stanceFootContactPoint(3) = q2 - c4*L; 


points.swingFootContactPoint(1) = q1 - s6*LShank - s5*LThigh; 
points.swingFootContactPoint(2) = 0; 
points.swingFootContactPoint(3) = q2 - c6*LShank - c5*LThigh; 


points.comVelocity(1) = u1 - s4*u4*legMassForwardOffset*MLeg*power(MLeg + ...
MPelvis + MShank + MThigh,-1) - ...
c4*u4*legMassVerticalOffsetBelowPelvis*MLeg*power(MLeg + MPelvis + MShank + ...
MThigh,-1) - s6*u6*MShank*swingShankMassForwardOffset*power(MLeg + MPelvis + ...
MShank + MThigh,-1) - ...
c6*u6*MShank*swingShankMassVerticalOffsetBelowPelvis*power(MLeg + MPelvis + ...
MShank + MThigh,-1) - s5*u5*MThigh*swingThighMassForwardOffset*power(MLeg + ...
MPelvis + MShank + MThigh,-1) - c5*u5*(LThigh*MShank + ...
MThigh*swingThighMassVerticalOffsetBelowPelvis)*power(MLeg + MPelvis + MShank ...
+ MThigh,-1); 
points.comVelocity(2) = 0; 
points.comVelocity(3) = u2 - c4*u4*legMassForwardOffset*MLeg*power(MLeg + ...
MPelvis + MShank + MThigh,-1) + ...
s4*u4*legMassVerticalOffsetBelowPelvis*MLeg*power(MLeg + MPelvis + MShank + ...
MThigh,-1) - c6*u6*MShank*swingShankMassForwardOffset*power(MLeg + MPelvis + ...
MShank + MThigh,-1) + ...
s6*u6*MShank*swingShankMassVerticalOffsetBelowPelvis*power(MLeg + MPelvis + ...
MShank + MThigh,-1) - c5*u5*MThigh*swingThighMassForwardOffset*power(MLeg + ...
MPelvis + MShank + MThigh,-1) + s5*u5*(LThigh*MShank + ...
MThigh*swingThighMassVerticalOffsetBelowPelvis)*power(MLeg + MPelvis + MShank ...
+ MThigh,-1); 


points.centerOfMassPosition(1) = c4*legMassForwardOffset*MLeg*power(MLeg + ...
MPelvis + MShank + MThigh,-1) - ...
s4*legMassVerticalOffsetBelowPelvis*MLeg*power(MLeg + MPelvis + MShank + ...
MThigh,-1) + (q1*MLeg + q1*MPelvis + q1*MShank + q1*MThigh)*power(MLeg + ...
MPelvis + MShank + MThigh,-1) + ...
c6*MShank*swingShankMassForwardOffset*power(MLeg + MPelvis + MShank + ...
MThigh,-1) - s6*MShank*swingShankMassVerticalOffsetBelowPelvis*power(MLeg + ...
MPelvis + MShank + MThigh,-1) + ...
c5*MThigh*swingThighMassForwardOffset*power(MLeg + MPelvis + MShank + ...
MThigh,-1) + s5*(-(LThigh*MShank) - ...
MThigh*swingThighMassVerticalOffsetBelowPelvis)*power(MLeg + MPelvis + MShank ...
+ MThigh,-1); 
points.centerOfMassPosition(2) = 0; 
points.centerOfMassPosition(3) = -(s4*legMassForwardOffset*MLeg*power(MLeg + ...
MPelvis + MShank + MThigh,-1)) - ...
c4*legMassVerticalOffsetBelowPelvis*MLeg*power(MLeg + MPelvis + MShank + ...
MThigh,-1) + (q2*MLeg + q2*MPelvis + q2*MShank + q2*MThigh)*power(MLeg + ...
MPelvis + MShank + MThigh,-1) - ...
s6*MShank*swingShankMassForwardOffset*power(MLeg + MPelvis + MShank + ...
MThigh,-1) - c6*MShank*swingShankMassVerticalOffsetBelowPelvis*power(MLeg + ...
MPelvis + MShank + MThigh,-1) - ...
s5*MThigh*swingThighMassForwardOffset*power(MLeg + MPelvis + MShank + ...
MThigh,-1) + c5*(-(LThigh*MShank) - ...
MThigh*swingThighMassVerticalOffsetBelowPelvis)*power(MLeg + MPelvis + MShank ...
+ MThigh,-1); 


points.velStanceFootContactPoint(1) = u1 - c4*u4*L; 
points.velStanceFootContactPoint(2) = 0; 
points.velStanceFootContactPoint(3) = u2 + s4*u4*L; 

